[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Accept, Accept-Language, Content-Type, Content-Language, Cache-Control"
    Access-Control-Expose-Headers = "Content-Length, Content-Range"
    Access-Control-Max-Age = "86400"
    Cache-Control = "public, max-age=3600"
